name: PVPMain
main: io.github.secondflight.PVPMain.PVPMain
version: 0.01

description: >
                 Main (maybe only idk lol) plugin for the awesome pvp thing
commands:

  item:
    description: for debugging
  pvpmain:
    description: Main command for the pvp plugin.